-- upgrade --
CREATE TABLE IF NOT EXISTS "pack" (
    "id" UUID NOT NULL  PRIMARY KEY,
    "name" VARCHAR(120) NOT NULL,
    "description" TEXT,
    "created" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "puzzle" (
    "id" UUID NOT NULL  PRIMARY KEY,
    "name" VARCHAR(64),
    "created" TIMESTAMPTZ NOT NULL  DEFAULT CURRENT_TIMESTAMP,
    "pack_id" UUID NOT NULL REFERENCES "pack" ("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "word" (
    "text" VARCHAR(64) NOT NULL  PRIMARY KEY
);
CREATE TABLE IF NOT EXISTS "wordpuzzle" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "role" VARCHAR(5),
    "puzzle_id" UUID NOT NULL REFERENCES "puzzle" ("id") ON DELETE CASCADE,
    "word_id" VARCHAR(64) NOT NULL REFERENCES "word" ("text") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "aerich" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "version" VARCHAR(255) NOT NULL,
    "app" VARCHAR(20) NOT NULL,
    "content" JSONB NOT NULL
);
